on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: Build & Release

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest  # Specify Linux environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Upload Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
